Algoritmo "AtividadeTerrenos"

Var
      L, C, M2, At, Pt: real



Inicio

      
      escreval("Digite a largura do terreno: ")
      leia(L)
      
      
      Escreval("Digite o coprimento do terreno: ")
      leia(C)
      
      
      Escreval("Digite o valor do metro quadrado: ")
      leia(M2)
      
      
      Escreval

      At <- L*C
      Pt <- M2*At
      
      Escreval("Area do Terreno= ",At:5:2)
      Escreval("Preço do Terreno= ",Pt:5:2)

Fimalgoritmo