Algoritmo "medidas"

Var

       Aq, Atri, Atra, A, B, C: real

Inicio

       Escreva("Digite a medida A: ")
       leia(A)
       Escreva("Digite a medida B: ")
       leia(B)
       Escreva("Digite a medida C: ")
       leia(C)
       
       Aq <- A^2
       Atri <- (A*B)/2
       Atra <- (A+B)*C/2


       Escreval("a área do quadrado: ",Aq)
       Escreval("a área do triângulo: ",Atri)
       Escreval("a área do trapézio: ",Atra)

Fimalgoritmo