Algoritmo "PAGAMENTO"

Var

       nome:caractere
       Vh,Qh,pagamento: real

Inicio

       Escreva("Nome do funcionário: ")
       Leia(nome)
       Escreva("Valor recebido por hora: ")
       leia(Vh)
       Escreva("Quantidade de horas trabalhadas: ")
       leia(Qh)
       
       pagamento <-Vh*Qh
       
       Escreva("O pagamento para ",nome," deve ser de: ",pagamento:5:2)
       


Fimalgoritmo